# Generated by Django 4.2.1 on 2023-06-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='one_unit_price',
        ),
    ]
